### ISSUE TITLE
 No module named 'ga_baseline'

### ISSUE THREAD

**Issue by jebert-1** [Jotels/ArtiSAN_Clean#1]
python New_Experiment.py
Traceback (most recent call last):
  File "/root/apps/ArtiSAN_Clean-main/src/Experiments/New_Experiment.py", line 15, in <module>
    from ga_baseline.prepare_db import get_starting_population
ModuleNotFoundError: No module named 'ga_baseline'

while we are running this command  ‘’python New_Experiment.py‘’ it gives error，ModuleNotFoundError: No module named 'ga_baseline' 。please give suggestion to resolve this issue。

**Comment by Jotels** [comment]
Hi there
The ga_baseline module is a legacy module that is not used anymore. You can remove the ga_baseline imports (as I have now done in the script too)

**Comment by mamubeen29** [comment]
Hi there 
When i have to run the code FORGE.py code as it, i have to set parameters manually also? Because when i tried to run this code first error showed,  en_atom_scaling = config["en_atom_scaling"]
KeyError: 'en_atom_scaling'          
if we put 'en_atom_scaling'= ''1'' then another key error shows. can you verifyor encounter this?

**Comment by Jotels** [comment]
Hi there

I have updated the code to not include these parameters anymore - they are once again just leftovers from a previous version that are not used anymore. You should replace the new version of the buffer.py and FORGE.py files to run the framework now. 

There might be other similar issues, and in almost all cases it should be possible to just comment out these parameters or lines of code.

**Comment by mamubeen29** [comment]
KeyError: 'num_baseline_randomizations'

**Comment by mamubeen29** [comment]
AttributeError: 'HEA' object has no attribute 'get_eom_proxy'

**Comment by Jotels** [comment]
Like I said, whenever there is a attributeerror or keyerror, just remove the calls that make the error.
